### ISSUE TITLE
Likelihood of Jira Data Center version or can I use Server version?

### ISSUE THREAD

**Issue by straff2002** [baloise/dashboard-plus#24]
I'm following up on behalf of one of our customers who is considering using your addon for their Data Center instance of Jira. 

Could you advise if your addon is or will be compatible with the DC version?

Many thanks, 
Greig

**Comment by greg-junkietech** [comment]
Hi Greig,

Strictly speaking, dashboard-plus does not fulfil all [guidelines for DC](https://developer.atlassian.com/platform/marketplace/guidelines-for-data-center-app-development/): it uses some deprecated APIs, makes blocking calls to external systems like Jenkins or Sonar...

Even it is not 100% safe to be used in DC installation in regards to these guidelines, dashboard-plus has been written since beginning with stability in mind and is currently used in 350+ installations, this probably includes also DC installations (no statistic available), so far without known problems.

Therefore I would encourage you and your customers to give it a try and probably to adopt it. Concrete feedback about DC experiences are welcome.

Bye & cheers,
Greg

**Comment by straff2002** [comment]
Thanks Greg, much appreciated. Guess we'll give it a go!
